name 'camunda'
maintainer ''
maintainer_email ''
license 'All Rights Reserved'
description 'Installs/Configures camunda'
long_description 'Installs/Configures camunda'
version '0.1.0'
chef_version '>= 13.0'
