name             'docker_registry_acs'
maintainer       ''
maintainer_email ''
license          'All rights reserved'
description      'Installs/Configures docker_registry_acs'
version          '0.4.1'

depends 'ssl_certificate'
depends 'docker_acs'
depends 'data_interface'
