provider "m3" {}

resource "m3_instance" "my-server" {
  image = "ubuntu18.04_64-bit"
  instance_name = "load-balancer"
  region_name = var.m3_region_name
  tenant_name = var.m3_tenant_name
  shape = "MEDIUM"
  enable_chef = true
  key_name = var.key_name
  owner = var.m3_owner
  chef_profile = "nginx_balancer"
  additional_data = {
    configuration = var.m3ah_configuration
    timestamp = var.m3_timestamp
  }
}

variable "m3_timestamp" {
  description = ""
}
variable "m3ah_configuration" {
  description = "Nginx conf generated by orch"
}
variable "region_name" {
  description = "Region"
}
variable "tenant_name" {
  description = "Tenant"
}
variable "key_name" {
  description = "key_name"
}
variable "owner" {
  description = "owner"
}