name 'gerrit_acs'
maintainer ''
maintainer_email ''
license 'All Rights Reserved'
description 'Installs/Configures gerrit_acs'
long_description 'Installs/Configures gerrit_acs'
version '0.2.0'
chef_version '>= 13.0'

depends 'corretto-java'